-- MySQL Script generated by MySQL Workbench
-- Wed Aug 22 11:01:39 2018
-- Model: Sakila Full    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ex_mysql
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ex_mysql
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ex_mysql` ;
USE `ex_mysql` ;

-- -----------------------------------------------------
-- Table `ex_mysql`.`TIMBRE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ex_mysql`.`TIMBRE` (
  `idTIMBRE` INT NOT NULL AUTO_INCREMENT,
  `timbre` VARCHAR(45) NULL,
  PRIMARY KEY (`idTIMBRE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ex_mysql`.`COLLECTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ex_mysql`.`COLLECTION` (
  `idCOLLECTION` INT NOT NULL AUTO_INCREMENT,
  `collection` VARCHAR(45) NULL,
  PRIMARY KEY (`idCOLLECTION`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ex_mysql`.`TIMBRE_has_COLLECTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ex_mysql`.`TIMBRE_has_COLLECTION` (
  `TIMBRE_idTIMBRE` INT NOT NULL,
  `COLLECTION_idCOLLECTION` INT NOT NULL,
  PRIMARY KEY (`TIMBRE_idTIMBRE`, `COLLECTION_idCOLLECTION`),
  CONSTRAINT `fk_TIMBRE_has_COLLECTION_TIMBRE`
    FOREIGN KEY (`TIMBRE_idTIMBRE`)
    REFERENCES `ex_mysql`.`TIMBRE` (`idTIMBRE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TIMBRE_has_COLLECTION_COLLECTION1`
    FOREIGN KEY (`COLLECTION_idCOLLECTION`)
    REFERENCES `ex_mysql`.`COLLECTION` (`idCOLLECTION`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_TIMBRE_has_COLLECTION_COLLECTION1_idx` ON `ex_mysql`.`TIMBRE_has_COLLECTION` (`COLLECTION_idCOLLECTION` ASC);

CREATE INDEX `fk_TIMBRE_has_COLLECTION_TIMBRE_idx` ON `ex_mysql`.`TIMBRE_has_COLLECTION` (`TIMBRE_idTIMBRE` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
